version: 2.1

jobs:
  chk_npm_lint_and_test:
    docker:
      # FIXME: sha3 package fails to build on latest node.js (version 17)
      - image: circleci/node:16
    resource_class: small
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm run test

workflows:
  version: 2
  workflow:
    jobs:
      - chk_npm_lint_and_test
